#!/usr/bin/env python3
"""
Build Registry Script

Scans all skill.yaml files in the aramb-skills repository and generates
a unified registry.yaml file containing skill IDs and menu descriptions
for LLM skill selection.

Usage:
    python scripts/build_registry.py

Output:
    registry.yaml in the repository root
"""

import yaml
import sys
from pathlib import Path
from datetime import datetime, timezone
from typing import List, Dict, Any


def find_skill_files(root_path: Path) -> List[Path]:
    """Find all skill.yaml files in the repository, excluding old structure."""
    skill_files = []

    # Define paths to include (new hierarchical structure)
    include_paths = [
        'meta',
        'frontend',
        'backend',
        'quality',
        'infrastructure',
        'testing',
    ]

    for include_path in include_paths:
        search_path = root_path / include_path
        if search_path.exists():
            for skill_yaml in search_path.rglob('skill.yaml'):
                skill_files.append(skill_yaml)

    return sorted(skill_files)


def load_skill(skill_path: Path) -> Dict[str, Any]:
    """Load a skill YAML file and extract relevant fields."""
    with open(skill_path, 'r') as f:
        data = yaml.safe_load(f)

    return {
        'id': data.get('id', ''),
        'name': data.get('name', ''),
        'version': data.get('version', ''),
        'menu_description': data.get('menu_description', data.get('description', '')),
        'tags': data.get('tags', []),
    }


def build_registry(root_path: Path) -> Dict[str, Any]:
    """Build the registry from all skill files."""
    skill_files = find_skill_files(root_path)

    skills = []
    for skill_path in skill_files:
        try:
            skill = load_skill(skill_path)
            if skill['id']:  # Only include skills with valid IDs
                skills.append({
                    'id': skill['id'],
                    'name': skill['name'],
                    'menu_description': skill['menu_description'],
                    'tags': skill['tags'],
                })
                print(f"  Loaded: {skill['id']} ({skill['name']})")
        except Exception as e:
            print(f"  Warning: Failed to load {skill_path}: {e}", file=sys.stderr)

    # Sort skills by ID for consistent output
    skills.sort(key=lambda s: s['id'])

    return {
        'version': '2.0.0',
        'generated_at': datetime.now(timezone.utc).isoformat(),
        'skill_count': len(skills),
        'skills': skills,
    }


def generate_registry_yaml(registry: Dict[str, Any]) -> str:
    """Generate the registry YAML content."""
    lines = [
        "# Skill Registry (Auto-generated)",
        "#",
        "# This file is automatically generated by scripts/build_registry.py",
        "# DO NOT EDIT MANUALLY - changes will be overwritten",
        "#",
        f"# Generated: {registry['generated_at']}",
        f"# Total skills: {registry['skill_count']}",
        "",
        f"version: \"{registry['version']}\"",
        f"generated_at: \"{registry['generated_at']}\"",
        f"skill_count: {registry['skill_count']}",
        "",
        "skills:",
    ]

    for skill in registry['skills']:
        lines.append(f"  - id: {skill['id']}")
        lines.append(f"    name: \"{skill['name']}\"")
        # Escape quotes in description
        desc = skill['menu_description'].replace('"', '\\"')
        lines.append(f"    menu_description: \"{desc}\"")
        if skill['tags']:
            lines.append(f"    tags: {skill['tags']}")
        lines.append("")

    return '\n'.join(lines)


def main():
    """Main entry point."""
    # Determine repository root (parent of scripts directory)
    script_path = Path(__file__).resolve()
    repo_root = script_path.parent.parent

    print(f"Building skill registry...")
    print(f"Repository root: {repo_root}")
    print()

    # Build registry
    print("Loading skills:")
    registry = build_registry(repo_root)
    print()

    # Generate YAML
    registry_yaml = generate_registry_yaml(registry)

    # Write to file
    output_path = repo_root / 'registry.yaml'
    with open(output_path, 'w') as f:
        f.write(registry_yaml)

    print(f"Registry written to: {output_path}")
    print(f"Total skills: {registry['skill_count']}")

    # Print skill menu (useful for debugging)
    print()
    print("=" * 60)
    print("SKILL MENU (for LLM selection)")
    print("=" * 60)
    for skill in registry['skills']:
        print(f"\n{skill['id']}")
        print(f"  {skill['menu_description']}")


if __name__ == '__main__':
    main()
